created classe
mariusbegby/TreningsAppen pull request #5
Opened 2023-10-04 20:23 UTC by bharatimainali

2023-10-07 17:14 UTC, mariusbegby requested changes
Please look at comments and make changes. There's a lot of things we dont need yet that can be removed.

2023-10-07 17:14 UTC, mariusbegby commented on .github/workflows/android.yml
Please do not change the workflow. Previous implementation was fine.

2023-10-07 17:14 UTC, mariusbegby commented on app/build.gradle.kts
> -        sourceCompatibility = JavaVersion.VERSION_1_8
Do not change this. We need version this for workflow build to run.

2023-10-07 17:14 UTC, mariusbegby commented on app/build.gradle.kts
> +    implementation("com.google.firebase:firebase-auth-ktx:22.1.2")
We will not implement firebase yet.

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/managers/NavigationManager.kt
only implement exercise class, not these other classes yet please

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/managers/SettingsManager.kt
same here, dont implement yet

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/models/TrainingPlanClass.kt
same here, dont implement yet

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/models/UserClass.kt
same here, dont implement yet

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/screens/HomeScreen.kt
What does this do?

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/utils/AuthenticationHelper.kt
same here, dont implement yet

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/utils/DatabaseHelper.kt
same here, dont implement yet

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/utils/Utils.kt
This does nothing currently, please delete. We dont need this yet.

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/res/layout/activity_main.xml
What does this do?

2023-10-07 17:14 UTC, mariusbegby commented on app/src/main/res/layout/fragment_home_screen.xml
What does this do?

2023-10-07 17:14 UTC, mariusbegby commented on gradle.properties
> +org.gradle.jvm.version=17
Why do we need this?

2023-10-07 20:11 UTC, bharatimainali commented on app/build.gradle.kts
> -        sourceCompatibility = JavaVersion.VERSION_1_8
done

2023-10-07 20:11 UTC, bharatimainali commented on app/build.gradle.kts
> +    implementation("com.google.firebase:firebase-auth-ktx:22.1.2")
done

2023-10-07 20:11 UTC, bharatimainali commented on app/src/main/java/com/example/treningsappen/managers/NavigationManager.kt
sure

2023-10-07 20:11 UTC, bharatimainali commented on app/src/main/java/com/example/treningsappen/managers/SettingsManager.kt
sure

2023-10-07 20:12 UTC, bharatimainali commented on app/src/main/java/com/example/treningsappen/utils/Utils.kt
//Inclasses you make klasser so i follow and also if we do not implement we can leave it like this
so we can use later if we need otherwise we can delete later.

2023-10-07 20:15 UTC, bharatimainali commented on app/src/main/java/com/example/treningsappen/utils/DatabaseHelper.kt
ok

2023-10-07 20:15 UTC, bharatimainali commented on app/src/main/java/com/example/treningsappen/utils/Utils.kt
ok

2023-10-07 20:46 UTC, bharatimainali commented on app/src/main/res/layout/activity_main.xml
In activity_main.xml, we specify the arrangement of user interface elements (such as buttons, text views, or images) and how they are displayed on the screen. It's like designing the sacred space where seekers gather to receive wisdom.

When the app is installed on a device, this layout is used to create the visual interface of the main activity, and users see this layout when they launch the app. This is the first step in their journey towards fitness and enlightenment.

2023-10-07 20:48 UTC, bharatimainali commented on app/src/main/res/layout/fragment_home_screen.xml
fragment_home_screen.xml: This XML file defines the layout for the home screen fragment within our app. and we specify how the home screen should look and what information should be displayed. This may include exercise recommendations, training plans, or inspirational messages. It's like presenting seekers with the teachings and practices they need to follow. and they installed them self when homescreen created

2023-10-07 20:48 UTC, bharatimainali commented on gradle.properties
> +org.gradle.jvm.version=17
ok

2023-10-07 20:49 UTC, bharatimainali commented on app/src/main/res/layout/fragment_home_screen.xml
screens: These are the different screens or views of your app.
HomeScreen: This is the main screen where users start their journey, like the beginning of one's spiritual quest.
onCreateView: Similar to the creation of one's path, this method sets up the initial view.
onViewCreated: This method can be seen as the revelation of truth, where the view is fully realized.

2023-10-09 10:57 UTC, mariusbegby requested changes
Please fix these changes as soon as possible.

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/managers/NavigationManager.kt
delete this file

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/managers/SettingsManager.kt
delete this file

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/models/ExerciseClass.kt
only call the class Exercise not ExerciseClass

the functions does not make sense, so please delete them for now

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/models/TrainingPlanClass.kt
delete this file, we do not need training plan yet

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/models/UserClass.kt
delete this file, we do not need user class yet

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/screens/HomeScreen.kt
What will this do? is this navigation bar? I think we should delete this for now until we implement proper navigation

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/utils/AuthenticationHelper.kt
delete this file, we do not need this yet

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/java/com/example/treningsappen/utils/DatabaseHelper.kt
delete this file, we do not need this yet

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/res/layout/activity_main.xml
what does this do? related to navigation? delete for now please

2023-10-09 10:57 UTC, mariusbegby commented on app/src/main/res/layout/fragment_home_screen.xml
what does this do? related to navigation? delete for now please

2023-10-09 10:57 UTC, mariusbegby commented on .github/workflows/android.yml
Remove these changes. Please do not modify CI/CD pipeline.

2023-10-09 10:57 UTC, mariusbegby commented on app/build.gradle.kts
Please discard these changes.

2023-10-09 20:59 UTC, mariusbegby commented on app/build.gradle.kts
@bharatimainali please still discard these changes.

2023-10-10 14:17 UTC, mariusbegby approved these changes
LGTM

2023-10-10 14:21 UTC, merged